name: Deploy on Docker Hub

on:
  release:
    types: [ published ]

jobs:
  # Following: https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images
  push_to_registry:
    runs-on: ubuntu-latest
    name: Push Docker image to Docker Hub
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: eurobenchtest/pi_bullet
        tag_with_ref: true
